### ISSUE TITLE
Handle placement is wrong

### ISSUE THREAD

**Issue by SimonCehlin** [oguzhaninan/vue-histogram-slider#12]
When setting the grid="false" the placement of the handles are slightly of:
![image](https://user-images.githubusercontent.com/41620469/81788297-9a55aa00-9502-11ea-841a-7c1843f10dc6.png)

When setting it to true it works:
![image](https://user-images.githubusercontent.com/41620469/81788256-8b6ef780-9502-11ea-965b-2f370c184acc.png)

**Comment by oguzhaninan** [comment]
Hi @SimonCehlin ,
Thanks for warning. I fixed this issue. Please check the new version.

**Comment by dukie66** [comment]
This issue is not fixed. I am using `"vue-histogram-slider": "^0.3.8",` version. 
` <HistogramSlider
                  width="100%"
                  :toFixed="true"
                  :fromFixed="true"
                  :grid="false"
                  :type="'double'"
                  :barHeight="0"
                  :min="1"
                  :max="10"
                  :step="1"
                  :handleSize="15"
                  :bar-height="100"
                  :data="range"
                />`
                
![image](https://user-images.githubusercontent.com/52957816/116689290-889c3980-a9d5-11eb-9878-6b93df21b5ee.png)

**Comment by pkaruga** [comment]
> vue-histogram-slider

I'm facing the same issue. Are you sure this is fixed?
