### ISSUE TITLE
Histogram doesn't react to data changes

### ISSUE THREAD

**Issue by diegonc** [oguzhaninan/vue-histogram-slider#7]
I set the data property to a computed property of the containing component and the slider doesn't update the bars.

If I change the section and then go back to where the slider is used then it updates. It seems that it only gets rendered on mount.

**Comment by oguzhaninan** [comment]
Thanks @diegonc. I wil fix it.

**Comment by KubeljK** [comment]
@oguzhaninan Has any progress been made on this issue?

**Comment by oguzhaninan** [comment]
Yes @KubeljK I fixed this issue.

**Comment by shahrizal96** [comment]
Hi I just notice that I got the same bug where the prop/data is changing but the bar is not updating.

**Comment by markusand** [comment]
What version was this fixed at? It doesn't seem to work in the CondeSandbox example using 0.3.8.
```vue
<template>
  <div id="app">
    <input
      type="range"
      min="0"
      max="1000"
      v-model.number="dataSize">
    <HistogramSlider
      :width="300"
      :data="data"
      :min="0"
      :max="Math.max(...data)"
    />
    {{ data }}
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return { dataSize: 100 };
  },
  computed: {
    data() {
      const { dataSize } = this;
      return [...Array(dataSize).keys()]
        .map(() => Math.round(Math.random() * 100));
    }
  },
};
</script>
```

**Comment by hsks** [comment]
Facing the same issue. Realtime data updates don't seem to be reflected.

**Comment by eugv86** [comment]
Still an issue... @hsks @markusand were you guys able to figure this out?

**Comment by dragma** [comment]
Still an issue. Anyone hasn't found any workaround still ?

**Comment by hadermendez** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
sunng87, @MichaIJarosz, @pjockey, @Foxsky28, @zihoo, @yasuharu519, @Puri12, @Lucroz94, @vj4a, @kil0rome0, @axifive, @Chamane, @athphane, @mrmorethanu, @zssvaidar, @magnus-cedulas, @zaherg, @hjoway, @a2k42, @Souldiv, @diminou91, @josefhs11, @flfcampos, @dnsergeev, @lordvins226, @hsomesun, @jianan1104, @lcs-felix, @asenov, @kajansasi, @leelianjason, @wkhayrattee, @SiroDiaz, @22mahmoud, @muzaparoff, @amoklilli, @904243852, @Bokonon366, @mozulamt, @mkoch66, @HolyFredy, @kuldeepat1lint, @caryxiao, @nulconaux, @ajq2679, @AmirZaidi65, @Valpluto, @FlaMaaSSteR, @rkrdo, @dapetoojoivo, @paulosiciliano, @bradneymkhwanazi, @karmicdude, @lsbloxx, @JFOC, @metajiji, @ruiz4real, @kaushikveluru, @tiagotcunha, @LoLo2207, @nashsophie, @coding-laura, @mkimartinez, @Oberfeldwedler, @leo-minorui, @rishabhnambiar, @MohiK98, @ieaster1, @Gechmir, @kenwoodjw, @lichw21, @christophengelmayer, @desaiViraj, @rainerh, @scirelli, @briehanlombaard, @m2candre, @rustyxlol, @aaw3, @dgk, @aminmr, @diabliya, @Abdellah5836, @handsomebaoxyz, @keepcleargas, @dannyh79, @nomadelog, @bj-pieri, @alansenairj, @sami-syed321, @littlebluepixel, @FilBot3, @defconxt, @greatchoice9527, @diwms, @WinkieWinkie, @ibaldov, @jeffcjohnson, @lastsky
